### ISSUE TITLE
Problem with the OpenCV example 

### ISSUE THREAD

**Issue by KiloNovemberDelta** [AprilRobotics/apriltags#2]
Hello,

Firstly, thank you for this great project, I really appreciate your effort to push forward the research field !

I'm writing here because I'm curious to try the version 3 of AprilTag. I'm used with the previous version.
So I have printed the Tag36h11 with the ID 0, from the git "Apriltag-imgs" 
![tag36_11_00000](https://user-images.githubusercontent.com/41945728/50344387-0e1c9e80-052b-11e9-9d39-1d6fd0a3dd06.png)
After printing it on a white piece of paper, I have downloaded this repository and compile it on my Ubuntu 16.04 machine. 

I have followed all the steps described by the README.md file, and when I run the OpenCV example, all works ok (with the command : ./opencv_demo ) and the video is displayed. 
But when I show the AprilTag on the camera, nothing happen. No AprilTag detected. 

I don't know if I have missed something, because it is supposed to be the basic example. I'm using the OpenCV 3.4.0.

Do you have any clue of what could happened ? Is it working in your side ? 

Thanks in advance for your time !

**Comment by mkrogius** [comment]
Hi,

Sorry to hear it didn't work right away. I tested this example just now and it works for me. Can you send me the image you are passing to the detector so I can debug it?

The AprilTag detector relies on detecting the edge between the outer white border and the black border. One thing to check is that this border is present on the tag you are using and that it is not occluded.

Best,
Max

**Comment by KiloNovemberDelta** [comment]
Sorry for the delay, I was on vacation. By the way, happy new year !

Please find in the folder following the picture generated by the program directly : 

[img_backup.zip](https://github.com/AprilRobotics/apriltags/files/2720854/img_backup.zip)

If I can provide anything else, do not hesitate.

**Comment by mkrogius** [comment]
Thanks for providing the images and bringing this bug to my attention.

It turns out that the png images in the repo (but not the ps files) had been generated with white+black colors reversed. The files have been corrected and it should work now.

**Comment by KiloNovemberDelta** [comment]
Glad to help. 

I have downloaded the last version of the git, and run it again.
Unfortunately, I still have 0 tag detected in the image with the same experience. 
Maybe the problem is something else ? 

I provide you the picture of this experience 
[2.zip](https://github.com/AprilRobotics/apriltags/files/2727350/2.zip)

Thanks again

**Comment by mkrogius** [comment]
Hi, sorry I don't think I was clear enough about the fix. You need to re-download the tag png files and print them out again. Let me know if you have any further issues

**Comment by KiloNovemberDelta** [comment]
Oh ok, I understand now. Everything is working, thanks !
