### ISSUE TITLE
Inconsistent order of corners

### ISSUE THREAD

**Issue by IanCarr-deAvelon** [AprilRobotics/apriltags#21]
I'm trying apriltag-2018-11-29.tgz with with Python using ctypes to access the .so.
I assumed that the order of the corners matches the marker, but that appears not to the the case. 
The comments in the code say:
    # p[4][2]: double The corners of the tag in image pixel coordinates. These always
    # wrap counter-clock wise around the tag.
If I have the tag vertical
![image](https://user-images.githubusercontent.com/23277223/55329464-ec6a7600-548e-11e9-80a5-6193d5caab48.png)
p[0] blue dot bottom left, p[1] green bottom right, p[2] red top right, p[3] white top left

If I turn more than 45 degrees
![image](https://user-images.githubusercontent.com/23277223/55329582-410df100-548f-11e9-9ca3-2e8488ad85e7.png)
Now p[0] blue top right of marker, p[1] green top left, p[2] bottom left and p[3] bottom right

Is this a bug (maybe fixed in later code) or I've failed to understand how the orientation of the marker on the square can be found?

Yours
Ian

**Comment by mkrogius** [comment]
Hi Ian,

Thanks for the bug report. This was fixed in https://github.com/AprilRobotics/apriltags/pull/4 so it should work correctly now.

Best,
Max
