### ISSUE TITLE
Error, more than one new minima found.

### ISSUE THREAD

**Issue by jkgarbe** [AprilRobotics/apriltags#22]
Hello, 
I edited the opencv_demo by adding the following because I am interested in pose:

//POSE DETECTION:
apriltag_detection_info_t info;
info.det = det;
info.tagsize = 100;
info.fx = 630;
info.fy = 630;
info.cx = 640;
info.cy = 360;
apriltag_pose_t pose;
double err = estimate_tag_pose(&info, &pose);
cout << "Err: " << err <<endl;

When I execute opencv_demo, it works for about 5 seconds, then crashes with this error:

Error, more than one new minima found.
*** Error in `./opencv_demo': free(): invalid pointer: 0x00007f01cd5ad81f ***
======= Backtrace: =========

Then it lists a bunch of locations.
How can I fix this?

**Comment by mkrogius** [comment]
Hi,

1) Does opencv_demo work with no edits made?
2) Can you please post the full output? I don't believe the "Error, more than one new minima found." is related to the crash.

Best,
Max

**Comment by jkgarbe** [comment]
@s-trinh Thank you! My issue is fixed.
